### ISSUE TITLE
Use environment variables to change the port

### ISSUE THREAD

**Issue by mnixry** [oott123/docker-novnc#6]
Case I want to be able to change the port using environment variables required for the program to avoid port conflicts, especially in the use of `network host` mode

**Comment by oott123** [comment]
Use this container in host network mode is highly discouraged as it need multiple TCP loopback ports. Changing ports on the fly will need dynamic configuration generated and that's why I don't like to add it. What's your use case btw?

**Comment by mnixry** [comment]
In fact I am using this project
https://github.com/CoolQ/docker-wine-coolq
Due to some requirements I have to start several of these containers and require them all to be able to connect directly to the host's port

If the dynamically generated configuration requires major changes to the program you can consider to close this issue, I would try to find another way :smile:

**Comment by oott123** [comment]
I think in your case you can create a docker network and put containers into it, then use -p to expose their ports.

If you still like to change ports, you can use bind mount to replace config files or start scripts, that will be fine, but please keep in mind that expose VNC ports to public may have security risks (you can add strong auth before nginx, but not VNC).

I'll close this issue for now but fell free to reopen or fire a new issue if you have further questions.
