### ISSUE TITLE
请问一个关于守护进程的事情

### ISSUE THREAD

**Issue by HzaZoro** [oott123/docker-novnc#7]
您好，我看在该程序中，也使用了s6 overlay，想知道，对于一个被s6管理的程序，该程序在启动了后发生了错误，导致挂掉，并被s6重新拉起，但是这个我想让它在多次拉起，还是报错了，就停止该程序。那我该如何配置呢？

**Comment by oott123** [comment]
不清楚，请去 https://github.com/just-containers/s6-overlay 提问
